import Foundation

struct Const {
    static let allCurrencies: [CurrencyType] = [
        .btc,
        .eth,
        .xrp,
        .bcc,
        .ada,
        .xem,
        .ltc,
        .xlm,
        .neo,
        .xmr,
        .qtum,
        .etc,
        .omg,
        .strat,
        .snt,
        .storj,
        .ark,
        .rep,
        .pivx,
        .powr,
        .emc2,
        .kmd,
        .btg,
        .sbd,
        .steem,
        .tix,
        .lsk,
        .waves,
        .mer,
        .grs,
        .vtc,
        .zec,
        .dash,
        .ardr,
    ]
}
